name: Symfony
on:
  push:
    branches: [ "main" ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: jardin_partage_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install JavaScript Dependencies
        run: |
          php bin/console importmap:install
          php bin/console asset-map:compile
      - name: Create Database
        env:
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/jardin_partage_test
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:schema:update --force
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/jardin_partage_test
        run: vendor/bin/phpunit

  symfony-deploy:
    needs: symfony-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: build-php
        name: "Install dependencies"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

        # Whitelist the public IP of the runner on the remote server by adding it to the SSH whitelist and wait 65 seconds for the IP to be whitelisted
      - shell: bash
        run: |
          curl -sX GET 'https://${{ secrets.SSH_USERNAME }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php' | fgrep 'index.live.php' | fgrep 'index.live.php?r=remove&address=' | cut -d '"' -f 2 | while read ipToRemove
          do 
            curl -sX GET 'https://${{ secrets.SSH_USERNAME }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/'$ipToRemove > /dev/null 2>&1
          done
          curl -X POST \
            -d 'whitelist[address]=${{ steps.ip.outputs.ipv4 }}' \
            -d 'whitelist[port]=22' \
            'https://${{ secrets.SSH_USERNAME }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=add'  > /dev/null 2>&1
          curl -sX GET 'https://${{ secrets.SSH_USERNAME }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php' | fgrep -q '${{ steps.ip.outputs.ipv4 }}' && echo "IP whitelisted"
          sleep 65
      - name: Deploy on main
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /public_html/
            git pull
            composer install
            php bin/console asset-map:compile
            php bin/console doctrine:migrations:migrate -n
            php bin/console cache:clear
            php bin/console cache:warmup
            chmod -R 777 var/*
            chmod -R 777 public/*
